#! /bin/bash
bell=`tput bel`
bold=`tput bold`
reset=`tput sgr 0`
yellow=`tput setaf 3`

if [ -d "$HOME/.cygnus" ]
then
  printf "\n${bold}${yellow}Cygnus is already installed!${reset}\n\n"
else
  mkdir "$HOME/.cygnus"
  cygnusPath="$_"
  mkdir "${cygnusPath}/templates"

  cp .cygnus-project/cygnus /usr/local/bin/
  cp .cygnus-project/cygnus-base/.help $cygnusPath
  cp -r .cygnus-project/cygnus-base/templates/* $cygnusPath/templates

  export PATH="/usr/local/bin:$PATH"

  printf "\n${bell}${yellow}${bold}Cygnus successfully installed!${reset}\n\n"

  cygnus -h
fi